lottery/urls.py
from django.conf.urls import patterns, url, include

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('lottery.views',
    (r'^admin/', include(admin.site.urls)),
    url('^$', 'index', name='index'),
    url('^json/?$', 'jsonf', name='jsonf'),
)

lottery/models.py
from django.db import models


class Ticket(models.Model):
    number = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.number

lottery/views.py
from annoying.decorators import render_to, ajax_request
from lottery.models import Ticket
from django import forms
from annoying.functions import get_object_or_None


class TicketForm(forms.Form):
    number = forms.CharField(max_length=50)


@render_to('lottery/index.html')
def index(request):
    result = None
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            result = get_object_or_None(Ticket, number=form.cleaned_data['number'])
    else:
        form = TicketForm()
    return {'form': form, 'result': result}


@ajax_request
def jsonf(request):
    result = get_object_or_None(Ticket, number=request.GET['number'])
    if result:
        return {'ticket': str(result)}
    return {}

lottery/templates/lottery/index.html
<html>
	<head>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<!--[if lte IE 8]>
		<script src="https://raw.githubusercontent.com/douglascrockford/JSON-js/master/json2.js"></script>
		<![endif]-->
		<script src="//cdn.ravenjs.com/1.1.15/raven.min.js"></script>
		<script>Raven.config('https://cae7c2f91ab542a38c459332e76cedfd@sentry.crop-r.com/8', {}).install();</script>
		<script>
		$(document).ready(function() {
			$('form').submit(function(e) {
			 	e.preventDefault();
				console.log('send form');
				$.ajax({
					url: "/json",
					dataType: "json",
					data: {number: $('#id_number').val()}
				}).done(function(data) {
					var html = data.ticket ? ('Yes, you won on ticket ' + data.ticket) : 'No, better luck next time';
					$("#result").html(html);
				}).fail(function(jqXHR, textStatus, errorThrown) {
					$("#result").html('sum thing wong: ' + errorThrown)
				});
			});
		});
		</script>
	</head>
	<body>
		<!--[if lte IE 8]>
			<div style="background-color:red;">Your browser is too old!</div>
		<![endif]-->
		<h1>Lottery!</h1>
		<h2>Did I win?</h2>
		<p id="result"> </p>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit"/>
		</form>
	</body>
</html>